name: Build & deploy

on:
   push:
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Deploy
           uses: easingthemes/ssh-deploy@v2.2.11
           env:
              SSH_PRIVATE_KEY: ${{ secrets.DEPLOYUSER_SSH_KEY }}
              REMOTE_HOST: ${{ secrets.DEPLOYUSER_HOST }}
              REMOTE_USER: ${{ secrets.DEPLOYUSER_USER }}
              REMOTE_PORT: ${{ secrets.DEPLOYUSER_PORT }}
              TARGET: "/srv/www/www.asteriski.fi/wp-content/plugins/wp-tenttiarkisto/"
           with:
             args: "-avz --no-perms --no-owner --no-group --omit-dir-times --progress"
