name: Build & deploy

on:
   push:
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Verify Source Directory
           run: ls -lah /home/runner/work/wp-tenttiarkisto/wp-tenttiarkisto
      
         - name: Deploy
           uses: easingthemes/ssh-deploy@v2.2.11
           env:
              SSH_PRIVATE_KEY: ${{ secrets.DEPLOYUSER_SSH_KEY }}
              REMOTE_HOST: ${{ secrets.DEPLOYUSER_HOST }}
              REMOTE_USER: ${{ secrets.DEPLOYUSER_USER }}
              REMOTE_PORT: ${{ secrets.DEPLOYUSER_PORT }}
              TARGET: "/srv/www/www.asteriski.fi/wp-content/plugins/wp-tenttiarkisto/"
              EXCLUDE: "/.git/"
           with:
             args: "-avz --progress"
